// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4MY6QgyQA8xr-wiBJVXAc6SMlDkiAoi0',
    appId: '1:196237624122:web:6020ebf2e8b54c31c80603',
    messagingSenderId: '196237624122',
    projectId: 'demodb-55bcc',
    authDomain: 'demodb-55bcc.firebaseapp.com',
    storageBucket: 'demodb-55bcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs8a-uktP4c7Dup6CxgYD7XOrgBKKBDmE',
    appId: '1:196237624122:android:a32355066e387364c80603',
    messagingSenderId: '196237624122',
    projectId: 'demodb-55bcc',
    storageBucket: 'demodb-55bcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjW-9rGUWgiVitLACu0V00_mvLzIdewtc',
    appId: '1:196237624122:ios:46dba58fd2d23147c80603',
    messagingSenderId: '196237624122',
    projectId: 'demodb-55bcc',
    storageBucket: 'demodb-55bcc.firebasestorage.app',
    iosBundleId: 'com.example.demodb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjW-9rGUWgiVitLACu0V00_mvLzIdewtc',
    appId: '1:196237624122:ios:46dba58fd2d23147c80603',
    messagingSenderId: '196237624122',
    projectId: 'demodb-55bcc',
    storageBucket: 'demodb-55bcc.firebasestorage.app',
    iosBundleId: 'com.example.demodb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4MY6QgyQA8xr-wiBJVXAc6SMlDkiAoi0',
    appId: '1:196237624122:web:eac9ff2c8bab14c2c80603',
    messagingSenderId: '196237624122',
    projectId: 'demodb-55bcc',
    authDomain: 'demodb-55bcc.firebaseapp.com',
    storageBucket: 'demodb-55bcc.firebasestorage.app',
  );
}
